// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbdZMN0tth1k58adgV5ouBrro-jZcAcpU',
    appId: '1:547076965680:android:a6a55ee7b91ccca92234f5',
    messagingSenderId: '547076965680',
    projectId: 'yong-project-8b980',
    storageBucket: 'yong-project-8b980.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOgEe9F2x1YjIT4rv0X5sFHYZnIW5dbJc',
    appId: '1:547076965680:ios:e874d50673f782bf2234f5',
    messagingSenderId: '547076965680',
    projectId: 'yong-project-8b980',
    storageBucket: 'yong-project-8b980.appspot.com',
    iosClientId:
        '547076965680-srsgvta2rdai4nr1bdn0fmhjfvb05755.apps.googleusercontent.com',
    iosBundleId: 'com.example.yongProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOgEe9F2x1YjIT4rv0X5sFHYZnIW5dbJc',
    appId: '1:547076965680:ios:e874d50673f782bf2234f5',
    messagingSenderId: '547076965680',
    projectId: 'yong-project-8b980',
    storageBucket: 'yong-project-8b980.appspot.com',
    iosClientId:
        '547076965680-srsgvta2rdai4nr1bdn0fmhjfvb05755.apps.googleusercontent.com',
    iosBundleId: 'com.example.yongProject',
  );
}
